import {
  deleteSession,
  getSessionInfo,
  getSessionMessages,
  listSessions,
  renameSession,
} from "@anthropic-ai/claude-agent-sdk";

/**
 * Reads Claude Code's own session history through the Agent SDK.
 *
 * Claude Code stores transcripts as JSONL under
 * `~/.claude/projects/<encoded-cwd>/<session-id>.jsonl`. The SDK owns that
 * format, so Studio never parses those files itself — if the layout changes,
 * an SDK upgrade carries the fix.
 */

/**
 * Session ids are UUIDs — both the ones Claude Code generates and the ones
 * Studio mints for a new chat. Anything else is a malformed client, and letting
 * it through means the id becomes a filename: a request carrying the literal
 * string "undefined" would create `undefined.jsonl` in the transcript store and
 * a junk conversation in the sidebar. Validate at the edge instead.
 */
const SESSION_ID_PATTERN =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export function isSessionId(value) {
  return typeof value === "string" && SESSION_ID_PATTERN.test(value);
}

// A single message carrying more inline image data than this is summarized
// instead of inlined, so one screenshot-heavy turn cannot bloat the transcript
// response into tens of megabytes.
const MAX_INLINE_IMAGE_BYTES = 4 * 1024 * 1024;

const NOISE_PATTERNS = [
  /^<command-name>/,
  /^<command-message>/,
  /^<local-command-stdout>/,
  /^<user-prompt-submit-hook>/,
  /^Caveat: The messages below were generated by the user while running local commands/,
];

function textIsNoise(text) {
  const trimmed = text.trim();
  if (!trimmed) {
    return true;
  }
  return NOISE_PATTERNS.some((pattern) => pattern.test(trimmed));
}

function stripSystemReminders(text) {
  return text.replace(/<system-reminder>[\s\S]*?<\/system-reminder>/g, "").trim();
}

function contentBlocks(message) {
  if (typeof message?.content === "string") {
    return [{ type: "text", text: message.content }];
  }
  return Array.isArray(message?.content) ? message.content : [];
}

function base64Bytes(data) {
  return Math.floor((String(data || "").length * 3) / 4);
}

function imageAttachment(block) {
  const source = block?.source || {};
  if (source.type === "base64" && source.data) {
    return {
      kind: "image",
      name: "Pasted image",
      dataUrl: `data:${source.media_type || "image/png"};base64,${source.data}`,
      bytes: base64Bytes(source.data),
    };
  }
  if (source.type === "url" && source.url) {
    return { kind: "image", name: "Linked image", url: source.url, bytes: 0 };
  }
  return null;
}

function toolSummary(block) {
  const input = block?.input && typeof block.input === "object" ? block.input : {};
  const detail =
    input.file_path ||
    input.path ||
    input.command ||
    input.pattern ||
    input.url ||
    input.description ||
    input.prompt ||
    "";
  return {
    id: block.id,
    name: block.name,
    detail: String(detail).slice(0, 200),
  };
}

/**
 * Collapses one stored transcript entry into the shape the UI renders, or
 * returns null when the entry is pure protocol traffic (tool results, hook
 * output, slash-command echoes).
 */
export function normalizeMessage(entry) {
  const role = entry?.type;
  if (role !== "user" && role !== "assistant") {
    return null;
  }

  const raw = entry.message;
  const blocks = contentBlocks(raw);
  const textParts = [];
  const thinkingParts = [];
  const tools = [];
  const attachments = [];
  let inlineBytes = 0;
  let hasToolResult = false;

  for (const block of blocks) {
    if (!block || typeof block !== "object") {
      continue;
    }
    if (block.type === "text" && typeof block.text === "string") {
      const text = stripSystemReminders(block.text);
      if (text && !textIsNoise(text)) {
        textParts.push(text);
      }
      continue;
    }
    if (block.type === "thinking" && typeof block.thinking === "string") {
      if (block.thinking.trim()) {
        thinkingParts.push(block.thinking);
      }
      continue;
    }
    if (block.type === "tool_use") {
      tools.push(toolSummary(block));
      continue;
    }
    if (block.type === "tool_result") {
      hasToolResult = true;
      continue;
    }
    if (block.type === "image") {
      const attachment = imageAttachment(block);
      if (attachment) {
        inlineBytes += attachment.bytes;
        attachments.push(attachment);
      }
      continue;
    }
    if (block.type === "document") {
      attachments.push({
        kind: "document",
        name: block.title || "Attached document",
      });
    }
  }

  if (inlineBytes > MAX_INLINE_IMAGE_BYTES) {
    for (const attachment of attachments) {
      if (attachment.kind === "image") {
        delete attachment.dataUrl;
        attachment.oversized = true;
      }
    }
  }

  const content = textParts.join("\n\n").trim();
  if (!content && !tools.length && !attachments.length) {
    return null;
  }
  // A user turn that only carries tool results is the harness talking to
  // itself — the tool chips on the preceding assistant turn already show it.
  if (role === "user" && hasToolResult && !content && !attachments.length) {
    return null;
  }

  return {
    id: entry.uuid,
    role,
    content,
    thinking: thinkingParts.join("\n\n") || undefined,
    tools,
    attachments,
    timestamp: typeof entry.timestamp === "string" ? entry.timestamp : undefined,
  };
}

function sessionRow(info) {
  const title = (info.customTitle || info.summary || info.firstPrompt || "").trim();
  return {
    id: info.sessionId,
    title: title || "Untitled session",
    preview: (info.firstPrompt || info.summary || "").trim().slice(0, 180),
    cwd: info.cwd || null,
    branch: info.gitBranch || null,
    createdAt: new Date(info.createdAt ?? info.lastModified ?? Date.now()).toISOString(),
    updatedAt: new Date(info.lastModified ?? Date.now()).toISOString(),
  };
}

export class SessionCatalog {
  constructor({ cacheMs = 2000 } = {}) {
    this.cacheMs = cacheMs;
    this.cache = null;
    this.cachedAt = 0;
    this.inFlight = null;
  }

  invalidate() {
    this.cache = null;
    this.cachedAt = 0;
  }

  /**
   * Every local Claude Code session, newest first. Programmatic/daemon
   * sessions are excluded so the sidebar mirrors what `claude --resume` shows.
   */
  async listSessions() {
    if (this.cache && Date.now() - this.cachedAt < this.cacheMs) {
      return this.cache;
    }
    if (this.inFlight) {
      return this.inFlight;
    }

    this.inFlight = (async () => {
      const sessions = await listSessions({ includeProgrammatic: false });
      const rows = sessions
        .map(sessionRow)
        .sort(
          (left, right) =>
            new Date(right.updatedAt).getTime() - new Date(left.updatedAt).getTime(),
        );
      this.cache = rows;
      this.cachedAt = Date.now();
      return rows;
    })();

    try {
      return await this.inFlight;
    } finally {
      this.inFlight = null;
    }
  }

  async getSession(sessionId) {
    const info = await getSessionInfo(sessionId);
    return info ? sessionRow(info) : null;
  }

  async getMessages(sessionId) {
    const entries = await getSessionMessages(sessionId);
    return entries.map(normalizeMessage).filter(Boolean);
  }

  async rename(sessionId, title) {
    await renameSession(sessionId, title);
    this.invalidate();
  }

  async delete(sessionId) {
    await deleteSession(sessionId);
    this.invalidate();
  }
}
